const mongoose = require('mongoose');

const findingSchema = new mongoose.Schema(
  {
    startup: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Startup',
      required: true,
    },
    type: {
      type: String,
      enum: ['contradiction', 'gap', 'self_correction', 'unsupported_claim'],
      required: true,
    },
    severity: {
      type: String,
      enum: ['low', 'medium', 'high'],
      required: true,
    },
    // The claims this finding is derived from — traceability is the whole point
    claimIds: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Claim',
        required: true,
      },
    ],
    // Generated by rules engine — deterministic, machine-readable
    ruleTriggered: {
      type: String,
      required: true,
      // e.g. 'paying_customers_gt_zero_and_revenue_zero', 'no_competitors_claimed'
    },
    // Generated by AI — human-readable explanation, communication layer only
    explanation: {
      type: String,
      default: null,
    },
    status: {
      type: String,
      enum: ['open', 'resolved'],
      default: 'open',
    },
  },
  { timestamps: true }
);

findingSchema.index({ startup: 1, status: 1 });

module.exports = mongoose.model('Finding', findingSchema);
